apiVersion: v2
name: spring
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
dependencies:
  - name: mysql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: 25.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: prometheus-mysql-exporter
    version: ~1.12.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: mysqlExporter.enabled
    alias: mysqlExporter
  - name: prometheus-kafka-exporter
    version: ~2.3.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: kafkaExporter.enabled
    alias: kafkaExporter
  - name: prometheus-redis-exporter
    version: ~5.3.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: redisExporter.enabled
    alias: redisExporter
